---
- name: Wait for opening port 9000
  ansible.builtin.wait_for:
    port: 9000
    delay: 10
    host: 127.0.0.1
- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc !=82
  changed_when: create_db.rc == 0